/*---------------copyright by Neil, You, Shanghai Jiaotong University 2016, 5 ------------------*/

/* known issue: Absolute position can only be calculated with a single canvas layer depth.
*               Mouse callback may prevent collision detection from working. */

var BASE64_CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=';

var ObjPool = {
    objects : [],
    Create : function() {
        var obj = {
            Destroy : function() {
                var index = ObjPool.objects.indexOf(this);
                ObjPool.objects.splice(index, 1);
            },
            absPos : function() {
                var absX = 0, absY = 0;

                if (this.hasOwnProperty("shape")) {
                    absX = this.shape.x;
                    absY = this.shape.y;
                } else {
                    absX = this.x;
                    absY = this.y;
                }
                var that = this;
                if (that.hasOwnProperty("parent")) {
                    var parent = that.parent;
                    absX += parent.x;
                    absY += parent.y;
                    /* that = that.parent; */
                }
                return {x:absX, y:absY};
            },
            __internal : {
                collidedObjects : []
            }
        };
        this.objects.push(obj);
        obj.rigid = false;
        return obj;
    }
};

var Mouse = {
    target : null,
    Attach : function(obj) {
        this.target = obj;
    },
    Detach : function() {
        this.target.Destroy();
        this.target = null;
    }
};

var PIdiv4 = 1.0 / 4.0 * Math.PI;
var EventManager = {
    currentMousePosition : {
        x : 0,
        y : 0
    },
    MouseUp : function(e) {
        if (Global.MOUSE_BLOCKED) return;
        var objs = ObjPool.objects.concat();
        for (var i = 0; i < objs.length; ++i) {
            var obj = objs[i];
            if (obj.hasOwnProperty("onClicked")) {
                if (this.currentMousePosition.x > (obj.absPos()).x && this.currentMousePosition.x < (obj.absPos()).x + obj.shape.width
                    && this.currentMousePosition.y > (obj.absPos()).y && this.currentMousePosition.y < (obj.absPos()).y + obj.shape.height)
                    obj.onClicked();
            }
        }
    },
    MouseMove : function(e) {
        if (Global.MOUSE_BLOCKED) return;
        this.currentMousePosition.x = e.localX;
        this.currentMousePosition.y = e.localY;
        if (Mouse.target != null) {
            Mouse.target.shape.x = e.localX - Mouse.target.shape.width / 2;
            Mouse.target.shape.y = e.localY - Mouse.target.shape.height / 2;
        }
        for (var i = 0; i < ObjPool.objects.length; ++i) {
            var obj = ObjPool.objects[i];

            if (this.currentMousePosition.x > (obj.absPos()).x && this.currentMousePosition.x < (obj.absPos()).x + obj.shape.width
                && this.currentMousePosition.y > (obj.absPos()).y && this.currentMousePosition.y < (obj.absPos()).y + obj.shape.height) {

                if((obj.__internal.catchMouse == null) || (obj.__internal.catchMouse == false)) {
                    obj.__internal.catchMouse = true;
                    if (obj.hasOwnProperty("onEntered")) {
                        obj.onEntered();
                    }
                }
            } else {
                if(obj.__internal.catchMouse == true) {
                    obj.__internal.catchMouse = false;
                    if (obj.hasOwnProperty("onLeaved")) {
                        obj.onLeaved();
                    }
                }
            }
        }
    },
    EnterFrame : function () {

        for (var i = 0; i < ObjPool.objects.length; ++i) {
            var obj = ObjPool.objects[i];
            if (obj.hasOwnProperty("onFrame")) {
                obj.onFrame();
            }
            if (obj.rigid && obj.hasOwnProperty("onCollision")) {
                var speed = {x:0, y:0};
                if (obj.__internal.lastPosition == null) {
                    obj.__internal.lastPosition = {
                        x : (obj.absPos()).x,
                        y : (obj.absPos()).y
                    };
                } else {
                    /*compute speed direction*/
                    speed.x = (obj.absPos()).x - obj.__internal.lastPosition.x;
                    speed.y = (obj.absPos()).y - obj.__internal.lastPosition.y;

                    obj.__internal.lastPosition.x = (obj.absPos()).x;
                    obj.__internal.lastPosition.y = (obj.absPos()).y;
                }



                for (var j = 0; j < ObjPool.objects.length; ++j) {
                    /*TODO(Neil): check pixel collision*/
                    var anotherObj = ObjPool.objects[j];
                    if (!anotherObj.rigid) continue;
                    if (anotherObj == obj) continue;

                    /*first one*/
                    var x1min = (obj.absPos()).x;
                    var x1max = (obj.absPos()).x + obj.shape.width;
                    var y1min = (obj.absPos()).y;
                    var y1max = (obj.absPos()).y + obj.shape.height;

                    /*second one*/
                    var x2min = (anotherObj.absPos()).x;
                    var x2max = (anotherObj.absPos()).x + anotherObj.shape.width - 1;
                    var y2min = (anotherObj.absPos()).y;
                    var y2max = (anotherObj.absPos()).y + anotherObj.shape.height - 1;

                    /*check*/
                    if (x1max > x2min && x1min < x2max && y1max > y2min && y1min < y2max) {
                        /*collided*/
                        if (obj.__internal.collidedObjects.indexOf(anotherObj) != -1) {
                            /*already in*/
                            continue;
                        }
                        obj.__internal.collidedObjects.push(anotherObj);

                        /*compute orientation*/
                        var direction;
                        var angle = Math.atan2(speed.y, speed.x);
                        if (angle <= 3 * PIdiv4 && angle > PIdiv4 ) {
                            direction = "DOWN";
                        } else if (angle <= PIdiv4 && angle > -PIdiv4) {
                            direction = "RIGHT";
                        } else if (angle <= -PIdiv4 && angle > -3 * PIdiv4) {
                            direction = "UP";
                        } else {
                            direction = "LEFT";
                        }
                        obj.onCollision(anotherObj, direction);
                    } else {
                        /*lost*/
                        var index = obj.__internal.collidedObjects.indexOf(anotherObj);
                        if (index != -1) {
                            /*already in*/
                            obj.__internal.collidedObjects.splice(index, 1);
                        }
                    }
                }
            }
        }
    }
};

/***********************************************************************/
function resetObject(object, param) {
    ScriptManager.popEl(object);
    if (param && param.parent) param.parent.addChild(object);
    else $.root.addChild(object);
    object.transform.matrix3D = null;
    return object;
}
/***********************************************************************/
function setParameters(object, param) {
    foreach(param,
        function(key, val) {
            if (object.hasOwnProperty(key)) object['' + key] = val;
        });
}
/***********************************************************************/
function eraseParameters(param, filter) {
    var newParam = {};
    foreach(param,
        function(key, val) {
            if (!filter.hasOwnProperty(key)) newParam['' + key] = val;
        });
    return newParam;
}


function createCanvas(param) {
    var object = resetObject($.createCanvas({
        lifeTime: 0
    }), param);
    setParameters(object, eraseParameters(param, {
        parent: 0
    }));
    return object;
}

function createText(str, param) {
    var object = resetObject($.createComment(str, {
        lifeTime: 0
    }), param);
    object.defaultTextFormat = $.createTextFormat('微软雅黑', (param && param.size) || 14, (param && param.color != null) ? param.color: 0xFFFFFF, false, false, false);
    object.filters = [];
    object.text = str;
    setParameters(object, eraseParameters(param, {
        parent: 0,
        size: 0,
        color: 0
    }));
    return object;
}

function fillRect(g, x, y, width, height, color) {
    g.graphics.beginFill(color);
    g.graphics.drawRect(x, y, width, height);
    g.graphics.endFill();
}

function abgr2rgba(data) {
    for (var i = 0; i < data.length / 2; i += 1) {
        var temp = data[i];
        data[i] = data[data.length - 1 - i];
        data[data.length - 1 - i] = temp;
    }
    return data;
}

function extract(data) {
    var bmd = Bitmap.createBitmapData(1, 1);
    var output = bmd.getPixels(bmd.rect);
    output.clear();
    var dataBuffer = [];
    dataBuffer.length = 4;
    var outputBuffer = [];
    outputBuffer.length = 3;
    var cnt = 0;
    for (var i = 0; i < data.length; i += 4) {
        for (var j = 0; j < 4 && i + j < data.length; j++) {
            dataBuffer[j] = BASE64_CHARS.indexOf(data.charAt(i + j));
        }

        /* attention, bgr to rgb convertion! */
        outputBuffer[0] = (dataBuffer[0] << 2) + ((dataBuffer[1] & 0x30) >> 4);
        outputBuffer[1] = ((dataBuffer[1] & 0x0f) << 4) + ((dataBuffer[2] & 0x3c) >> 2);
        outputBuffer[2] = ((dataBuffer[2] & 0x03) << 6) + dataBuffer[3];
        for (var k = 0; k < outputBuffer.length; k++) {
            if (dataBuffer[k + 1] == 64) break;
            if (cnt >= 54) { /* skip bmp header */
                /*if (cnt % 3 == 1) {
                    output.writeByte(0);
                };*/

                output.writeByte(outputBuffer[k]);
            }
            cnt++;
        }
    }
    output = abgr2rgba(output);
    output.position = 0;
    return output;
}

function loadBitmapData(width, height, raw) {
    var bmd = Bitmap.createBitmapData(width, height);
    /* trace((extract(raw)).length); */
    bmd.setPixels(bmd.rect, extract(raw));
    return bmd;
}

function createBitmap(bitmapData, lifeTime, scale, parent) {
    var bmp = Bitmap.createBitmap({
        bitmapData: bitmapData,
        lifeTime: lifeTime,
        parent: parent,
        scale: scale
    });
    return bmp;
}

function createBMPObj(width, height, bmp_type, type, lifetime, scale, parent) {
    var obj = ObjPool.Create();
    var raw = Global.RESOURCES.BITMAPS[bmp_type];
    var bmd;
    if (Global.CACHE.BMD.hasOwnProperty(raw)) {
        bmd = Global.CACHE.BMD[raw];
    } else {
        bmd = loadBitmapData(width, height, raw);
        Global.CACHE.BMD[raw] = bmd;
    }
    obj.shape = createBitmap(bmd, lifetime, scale, parent);
    obj.bmp_type = bmp_type;
    obj.type = type;
    obj.parent = parent;
    return obj;
}
/***********************************************************************/
/***********************************************************************/
/***********************************************************************/

function createRectangle(parent, color, x, y) {
    var g = $.createShape({parent: parent, lifeTime:0, x:0, y:0, name:"bg"});
    g.graphics.beginFill(color);
    g.graphics.drawRect(0,0,x,y);
    g.graphics.endFill();
    return g;
}

var Global = {
    PLAYER : {},
    MAP: [],
    MAP_SIZE: {
      x : 13,
      y : 13
    },
    TYPE: {
        NPC_TRADE: "NPC_TRADE",
        KEY_YELLOW : "KEY_YELLOW",
        KEY_RED : "KEY_RED",
        PLAYER : "PLAYER",
        SLM_GREEN : "SLM_GREEN",
        BACKGROUND : "BACKGROUND"
    },
    BLOCK_SIZE: {
        x : 0,
        y : 0
    },
    DATA : {
        PLAYER : {
            HP : 999999,
            ATK : 10,
            DEF : 10,
            GOLD : 0,
            EXP : 0
        },
        SLM_GREEN : {
            HP : 50,
            ATK : 10,
            DEF : 0,
            GOLD : 2,
            EXP : 1,
            SPECIAL : {}
        },
        NPC_TRADE : {},
        KEY_YELLOW : {}
    },
    MAP_SCALE: 0,
    RESOURCES : {
        BITMAPS : {
            KEY_YELLOW: "Qk02EAAAAAAAADYAAAAoAAAAIAAAACAAAAABACAAAAAAAAAQAADEDgAAxA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGaIu/9miLv/Zoi7/2aIu/9miLv/Zoi7/2aIu/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGaIu/9miLv/iKrd/4iq3f+Iqt3/iKrd/4iq3f+Iqt3/iKrd/2aIu/9miLv/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABmiLv/iKrd/4iq3f+Iqt3/iKrd/6rM//+qzP//qsz//6rM//+Iqt3/iKrd/4iq3f9miLv/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZoi7/4iq3f+Iqt3/iKrd/4iq3f+Iqt3/iKrd/4iq3f+qzP//qsz//6rM//+qzP//iKrd/4iq3f9miLv/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABmiLv/iKrd/4iq3f+Iqt3/RGaZ/0Rmmf9EZpn/iKrd/4iq3f+qzP//qsz//6rM//+qzP//iKrd/2aIu/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZoi7/4iq3f+Iqt3/iKrd/0Rmmf9EZpn/RGaZ/0Rmmf9EZpn/iKrd/6rM//+qzP//qsz//6rM//+Iqt3/iKrd/2aIu/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABmiLv/iKrd/4iq3f+Iqt3/RGaZ/0Rmmf9EZpn/RGaZ/0Rmmf+Iqt3/qsz//6rM//+qzP//qsz//6rM//+Iqt3/Zoi7/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGaIu/+Iqt3/qsz//4iq3f9EZpn/RGaZ/0Rmmf9EZpn/RGaZ/4iq3f+qzP//qsz//6rM//+qzP//qsz//4iq3f9miLv/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZoi7/4iq3f+qzP//iKrd/4iq3f9EZpn/RGaZ/0Rmmf+Iqt3/iKrd/6rM//+qzP//qsz//6rM//+qzP//iKrd/2aIu/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABmiLv/iKrd/6rM//+qzP//iKrd/4iq3f+Iqt3/iKrd/4iq3f+qzP//qsz//6rM//+qzP//qsz//6rM//+Iqt3/Zoi7/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGaIu/+Iqt3/qsz//6rM//+qzP//qsz//6rM//+qzP//qsz//6rM//+qzP//qsz//6rM//+qzP//qsz//4iq3f9miLv/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZoi7/4iq3f+Iqt3/qsz//6rM//+qzP//qsz//6rM//+qzP//qsz//6rM//+qzP//qsz//6rM//+qzP//iKrd/2aIu/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZoi7/4iq3f+qzP//qsz//6rM//+qzP//qsz//6rM//+qzP//qsz//6rM//+qzP//qsz//6rM//+Iqt3/iKrd/2aIu/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABmiLv/iKrd/4iq3f+qzP//qsz//6rM//+qzP//qsz//6rM//+qzP//iKrd/4iq3f+Iqt3/qsz//6rM//+Iqt3/Zoi7/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABmiLv/iKrd/4iq3f+Iqt3/qsz//6rM//+qzP//qsz//4iq3f+Iqt3/iKrd/4iq3f+Iqt3/qsz//6rM//+Iqt3/Zoi7/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABmiLv/Zoi7/4iq3f+Iqt3/iKrd/4iq3f+Iqt3/iKrd/2aIu/9miLv/Zoi7/4iq3f+Iqt3/qsz//6rM//+Iqt3/Zoi7/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZoi7/2aIu/9miLv/Zoi7/2aIu/9miLv/AAAAAAAAAAAAAAAAiKrd/4iq3f+Iqt3/qsz//6rM//+Iqt3/Zoi7/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiKrd/4iq3f+Iqt3/qsz//6rM//+Iqt3/Zoi7/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIqt3/iKrd/4iq3f+Iqt3/qsz//6rM//+Iqt3/Zoi7/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIiq3f+Iqt3/qsz//6rM//+Iqt3/Zoi7/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiKrd/4iq3f+Iqt3/qsz//6rM//+Iqt3/Zoi7/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIqt3/iKrd/4iq3f+Iqt3/qsz//6rM//+Iqt3/Zoi7/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIiq3f+Iqt3/iKrd/4iq3f+Iqt3/qsz//6rM//+Iqt3/Zoi7/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIiq3f+Iqt3/qsz//4iq3f9miLv/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiKrd/4iq3f+Iqt3/iKrd/2aIu/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIqt3/iKrd/4iq3f+Iqt3/Zoi7/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
            NPC001: "Qk02EAAAAAAAADYAAAAoAAAAIAAAACAAAAABACAAAAAAAAAQAADEDgAAxA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC7iIj/u4iI/7uIiP+7iIj/u4iI/7uIiP+7iIj/u4iI/7uIiP+7iIj/u4iI/7uIiP+7iIj/u4iI/7uIiP+7iIj/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAu4iI/7uIiP/dqqr/3aqq/92qqv/dqqr/3aqq/92qqv/dqqr/3aqq/92qqv/dqqr/3aqq/92qqv/dqqr/3aqq/7uIiP+7iIj/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALuIiP+7iIj/3aqq/92qqv/dqqr/3aqq/92qqv/dqqr/3aqq/92qqv/dqqr/3aqq/92qqv/dqqr/3aqq/92qqv/dqqr/3aqq/7uIiP+7iIj/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAu4iI/92qqv/dqqr/3aqq///MzP//zMz//8zM///MzP//zMz//8zM///MzP//zMz/3aqq/92qqv/dqqr/3aqq/92qqv/dqqr/3aqq/7uIiP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC7iIj/3aqq/92qqv//zMz//8zM///MzP//zMz//8zM///MzP//zMz//8zM///MzP//zMz//8zM/92qqv/dqqr/3aqq/92qqv/dqqr/u4iI/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALuIiP+7iIj/3aqq///MzP//zMz//8zM///MzP//zMz//8zM///MzP//zMz//8zM///MzP//zMz//8zM/92qqv/dqqr/3aqq/7uIiP+7iIj/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALuIiP/dqqr/3aqq///MzP//zMz//8zM///MzP//zMz//8zM///MzP//zMz//8zM///MzP//zMz/3aqq/92qqv/dqqr/u4iI/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALuIiP+7iIj/u4iI/wAAAAAAAAAAu4iI/7uIiP/dqqr//8zM///MzP//zMz//8zM///MzP//zMz//8zM///MzP//zMz//8zM///MzP/dqqr/3aqq/7uIiP+7iIj/AAAAAAAAAAC7iIj/u4iI/7uIiP8AAAAAAAAAAAAAAAC7iIj/u4iI/7uIiP+7iIj/u4iI/wAAAAAAAAAAu4iI/92qqv/dqqr//8zM///MzP//zMz//8zM///MzP//zMz//8zM///MzP//zMz/3aqq/92qqv/dqqr/u4iI/wAAAAAAAAAAu4iI/7uIiP+7iIj/u4iI/7uIiP8AAAAAAAAAALuIiP9mZmb/ZmZm/7uIiP+7iIj/u4iI/7uIiP+7iIj/3aqq/92qqv/dqqr/3aqq///MzP//zMz//8zM///MzP//zMz//8zM/92qqv/dqqr/3aqq/92qqv+7iIj/u4iI/7uIiP+7iIj/u4iI/2ZmZv9mZmb/u4iI/wAAAAAAAAAAu4iI/2ZmZv9mZmb/u4iI/92qqv/dqqr/u4iI/7uIiP+7iIj/u4iI/92qqv/dqqr/3aqq/92qqv/dqqr/3aqq/92qqv/dqqr/3aqq/92qqv+7iIj/u4iI/7uIiP+7iIj/3aqq/92qqv+7iIj/ZmZm/2ZmZv+7iIj/AAAAAAAAAAC7iIj/ZmZm/2ZmZv+7iIj/3aqq/92qqv/dqqr/3aqq/92qqv/dqqr/3aqq/92qqv/dqqr/3aqq/92qqv/dqqr/3aqq/92qqv/dqqr/3aqq/92qqv/dqqr/3aqq/92qqv/dqqr/3aqq/7uIiP9mZmb/ZmZm/7uIiP8AAAAAAAAAAGaIu/9miLv/Zoi7/7uIiP/dqqr/3aqq///MzP//zMz//8zM/92qqv/dqqr/3aqq/92qqv/dqqr/3aqq/92qqv/dqqr/3aqq/92qqv/dqqr//8zM///MzP//zMz//8zM/92qqv/dqqr/u4iI/2aIu/9miLv/Zoi7/wAAAAAAAAAAZoi7/6rM//+Iqt3/u4iI/92qqv//zMz//8zM///MzP//zMz//8zM/92qqv/dqqr/3aqq/7uIiP+7iIj/u4iI/7uIiP/dqqr/3aqq///MzP//zMz//8zM///MzP//zMz/3aqq/92qqv+7iIj/iKrd/6rM//9miLv/AAAAAAAAAABmiLv/qsz//4iq3f+7iIj/3aqq///MzP//zMz//8zM///MzP//zMz/3aqq/92qqv+7iIj/zMzM/8zMzP/MzMz/zMzM/7uIiP/dqqr/3aqq///MzP//zMz//8zM///MzP/dqqr/3aqq/7uIiP+Iqt3/qsz//2aIu/8AAAAAAAAAAGaIu/9miLv/iKrd/7uIiP/dqqr//8zM///MzP//zMz//8zM/92qqv/dqqr/u4iI/8zMzP/MzMz////////////MzMz/zMzM/7uIiP/dqqr/3aqq///MzP//zMz//8zM/92qqv/dqqr/u4iI/4iq3f9miLv/Zoi7/wAAAAAAAAAAAAAAAGaIu/9miLv/u4iI/92qqv//zMz//8zM///MzP/dqqr/3aqq/7uIiP/MzMz/zMzM///////////////////////MzMz/zMzM/7uIiP/dqqr/3aqq///MzP//zMz/3aqq/92qqv+7iIj/Zoi7/2aIu/8AAAAAAAAAAAAAAAAAAAAAu4iI/7uIiP+7iIj/3aqq/92qqv/dqqr/3aqq/92qqv+7iIj/zMzM/8zMzP/////////////////////////////////MzMz/zMzM/7uIiP/dqqr/3aqq/92qqv/dqqr/3aqq/7uIiP+7iIj/u4iI/wAAAAAAAAAAAAAAAAAAAAAAAAAAu4iI/7uIiP/dqqr/3aqq/92qqv/dqqr/3aqq/7uIiP/MzMz////////////////////////////////////////////MzMz/u4iI/92qqv/dqqr/3aqq/92qqv/dqqr/u4iI/7uIiP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAu4iI/7uIiP+7iIj/3aqq/92qqv+7iIj/zMzM/8zMzP///////////4iq3f+Iqt3/iKrd/4iq3f///////////8zMzP/MzMz/u4iI/92qqv/dqqr/u4iI/7uIiP+7iIj/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALuIiP+7iIj/u4iI/7uIiP/MzMz///////////+Iqt3/qsz//6rM//+qzP//qsz//4iq3f///////////8zMzP+7iIj/u4iI/7uIiP+7iIj/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzMzM/8zMzP//////////////////////////////////////////////////////zMzM/8zMzP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMzMz///////////+Iqt3/iKrd/4iq3f+Iqt3/iKrd/4iq3f+Iqt3/iKrd////////////zMzM/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMzMzP9miLv/iKrd/4iq3f+qzP//qsz//6rM//+qzP//qsz//4iq3f+Iqt3/iKrd/2aIu//MzMz/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARGaZ/2aIu/+Iqt3/IkR3/yJEd/8iRHf/qsz//6rM//8iRHf/IkR3/yJEd/+Iqt3/Zoi7/0Rmmf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABEZpn/Zoi7/6rM//////////////////+qzP//qsz//////////////////4iq3f9miLv/RGaZ/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABEZpn/////////////////zMzM/4iq3f+Iqt3/zMzM/////////////////0Rmmf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAERmmf9miLv/Zoi7/4iq3f+Iqt3/iKrd/4iq3f+Iqt3/iKrd/2aIu/9miLv/RGaZ/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAERmmf9EZpn/Zoi7/2aIu/+Iqt3/iKrd/2aIu/9miLv/RGaZ/0Rmmf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABEZpn/RGaZ/0Rmmf9EZpn/RGaZ/0Rmmf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
            WARRIOR_BLUE: "Qk2KEAAAAAAAAIoAAAB8AAAAIAAAACAAAAABACAAAwAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAD/AAD/AAAAAAAA/0JHUnOPwvUoUbgeFR6F6wEzMzMTZmZmJmZmZgaZmZkJPQrXAyhcjzIAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALqJh/+5h4f/uoiK/7qKif+6ion/uYeH/7qKif+6iYf/AAAAAAAAAAC6iIr/uYeH/7qKif+5h4f/uoqJ/7mHh/+6iIr/uomH/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAuoiK/9yqqv/cqqr/3Kqq/9yqqv//zc3//s3L/9yqqv+6ion/uoiK/9yqqv/+zM7//cvL/9yqqv/cqqr/3Kqq/9yqqv+6ion/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC6ion/uoiK/96qqv/9y8v//83N//7Ny///zc3/3qqq/72Jif+6ion/26qs//7+/v/+zM7//szO//3Ly//eqqr/uoiK/7qKif8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC6iYf/uoqJ/7qIiv+5h4f/uoiK/7mHh//Mzcv/AAAAAAAAAADPzc3/uoqJ/7qKif+6iYf/uoiK/7mHh/+6iYf/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzMvN/8vLy/+6ion/uYeH/83Nzf8AAAAAAAAAAMzNy//+/v7//v7+/8zLzf/Mzcv/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALqIiv+5h4f/z83N//7+/v/Nzc3/zMvN/wAAAAAAAAAAy8vL//7+/v/+/v7/zc3N/7qJh/+6ion/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC6iIr/3Kqq/96qqv+6iYf/y8vL/7qKif+6iYf/uoiK/7qKif+6ion/uoqJ/8vLy/+6iYf/3Kqq/9yqqv+5h4f/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAuoqJ/96qqv/+zM7//s3L//3Ly/+6iIr/3qqq///Nzf/9y8v//83N//3Ly//eqqr/uoiK//3Ly///zc3/uoiK/7qKif8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGaJu/9mibv/Zom7/wAAAAAAAAAAuoqJ/96qqv/9y8v//szO/7qKif/eqqr//cvL///Nzf/9y8v//83N//7Mzv+6ion/3Kqq//7+/v/eqqr/uomH/wAAAAAAAAAAZom7/2WJuf9mibv/AAAAAAAAAAAAAAAAAAAAAAAAAABmibv/qcz+/6nM/v+pzP7/Zom7/wAAAAC6ion/uYeH/96qqv/eqqr/uoiK/96qqv/cqqr//cvL///Nzf/9y8v/3qqq/7mHh//cqqr//cvL/7qJh/+5h4f/AAAAAGaJu/+oy/3/qcz+/6nL//9mibv/AAAAAAAAAAAAAAAAAAAAAGaJu/+pzP7/qcv//4ap2/9mibv/AAAAAAAAAAC6ion/uoiK/7qIiv+6ion/uYeH/7qKif/cqqr/3qqq/7mHh/+6iIr/uomH/7qIiv/eqqr/uoqJ/wAAAAAAAAAAZom7/4ap2/+oy/3/qMv9/2aJu/8AAAAAAAAAAAAAAAAAAAAAz83N/2aJu/9mibv/Zom7/8vLy/8AAAAAAAAAAAAAAAC6ion/3Kqq///Nzf/9y8v/3Kqq/7qJh/+6ion/3Kqq//7Ny//9y8v/3qqq/7qIiv8AAAAAAAAAAAAAAADMzcv/Zom7/2SJu/9mibv/y8vL/wAAAAAAAAAAAAAAAAAAAADMy83//v7+//7+/v/+/v7/zc3N/8/Nzf8AAAAAuYeH/9yqqv/+/v7//v7+//7Mzv//zc3/uYeH/7qJh//9y8v//cvL//7Mzv//zc3/3qqq/7mHh/8AAAAAzMvN/8zNy/9mibv/Zom7/2SJu//Nzc3/AAAAAAAAAAAAAAAAAAAAAMzNy//+/v7//v7+//7+/v/+/v7/z83N/7mHh//cqqr//szO//7+/v//zc3//cvL//3Ly/+6iIr/uoiK//3Ly//+zM7//s3L//3Ly//+zM7/3Kqq/7qKif/My83/zM3L/8zLzf/+/v7//v7+/83Nzf8AAAAAAAAAAAAAAAAAAAAAz83N/8/Nzf/Ly8v/zMvN/8vLy//Ly8v/uoiK/9yqqv/+zM7//s3L//3Ly/+6iIr/uYeH/7qKif+6iYf/uoqJ/7qJh//9y8v//szO/9yqqv/cqqr/uoiK/8zNy//Ly8v/z83N/8vLy//Mzcv/zc3N/wAAAAAAAAAAAAAAAAAAAADMy83/uoiK/7qJh/+6ion/uoiK/7qJh//cqqr/3qqq/9yqqv/9y8v/uYeH/9yqqv/9zcz//s3L/9yqqv/crKv/3Kqq/7qJh//bqqz/3qqq/9yqqv/cqqr/uoiK/7mHh/+5h4f/uoqJ/7mHh//Pzc3/AAAAAAAAAAAAAAAAAAAAALqKif/cqqr/3Kqq/96qqv/eqqr/3qqq/7mHh/+6iIr/3Kqq/9yqqv+6ion//s3L/9yqqv/cqqr/3Kqq/9yqqv/cqqr/uoiK/7qJh/+6ion/uoqJ/7mHh//cqqr/3qqq/96qqv/eqqr/3Kqq/7qKif8AAAAAAAAAAAAAAAC6ion/3qqq/7qIiv+6ion/uoqJ/7mHh/+6ion/3Kqq/9yqqv+6iYf/uYeH/9yqqv/cqqr/3Kqq/9yqqv/cqqr/3Kqq/9uqrP/eqqr/uoiK/7mHh//eqqr/3Kqq/7qIiv+5h4f/uomH/7qIiv+9iYn/3qqq/7mHh/8AAAAAvYmJ/96qqv+5h4f//83N//3Ly///zc3//cvL///Nzf+6ion/uomH/9yqqv/cqqr/uoqJ/9yqqv9DZZr/RWaX/0RomP9FZpf/3Kqq/7qJh//cqqr/uoqJ/7mHh/+6ion//cvL//7Mzv//zc3//cvL//3Ly/+6ion/3Kqq/7qKif+6iIr/uYeH//7Mzv/+/v7//83N///Nzf/9y8v//83N//3Ly//crKv/uoiK/9yqqv9DZZr/RWaX/2SJu/+Fqtz/iKvd/2aJu/9FZpf/RWaX/9yqqv+6iYf/3Kqq///Nzf/9y8v//s3L//3Ly///zc3//cvL///Nzf+6iIr/uYeH/7qKif/cqqr/3Kqq//7+/v/+/v7//s3L///Nzf//zc3//cvL/9yqqv+6ion/RWaX/2SJu/+Iq93/qcz+/6nM/v+pzP7/hqnb/4ap2/9mibv/RWaY/wAAAADeqqr//cvL//7Mzv/+zcv//szO//7Ny//eqqr/3Kqq/96qqv+6ion/AAAAALqKif/eqqr/3Kqq//7Mzv/9y8v//cvL/96qqv+6ion/uomH/wAAAABFZpf/iKvd/6nM/v+pzP7/qcz+/6nM/v+pzP7/iKvd/4ap2/9FZpf/AAAAALqJh/+6ion/3qqq//3Ly//9y8v//szO/96qqv/eqqr/uYeH/wAAAAAAAAAAAAAAALqKif+6iYf/uoiK/7qKif+6ion/AAAAAAAAAAAAAAAARWaX/2SJu/+pzP7/qcz+/6nM/v+pzP7/qcz+/6jL/f+Iq93/hqnb/2aJu/9DZZr/AAAAAAAAAAC6iYf/uoiK/7qKif+6iYf/uoiK/7qKif8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACJFd/9DZZr/hqnb/6nM/v8gQ3X/IEN1/6nM/v+pzP7/IEN1/yFFdf+Iq93/hqnb/0VmmP8iRXf/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIkV3/yBDdf9kibv/iKvd/4ir3f+Iq93/qMv9/6jL/f+Iq93/hqnb/yBDdf9kibv/IEN1/yJFd/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiRXf/IEN1/yFFdf9mh7n/harc/yFFdf+Iq93/harc/4ir3f8hRXX/Q2Wa/yFFdf8hRXX/IkN1/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACJFd/9DZZr/IUV1/yFFdf8hRXX/Q2Wa/yFFdf+Iq93/IEN1/yBDdf8hRXX/IkV3/0Nlmv8iRXf/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIkV3/yJFd/9FZpf/IUV1/0Nlmv8hRXX/Q2eX/yFFdf8hRXX/IUV1/0Vml/8hRXX/IEN1/yJFd/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIEN1/yFFdf9FZpf/RWaX/0Nlmv9FZpf/Q2Wa/yJEef9FZpf/IkV3/0Vml/8iRXf/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiRXf/IkV3/0Vml/9DZZr/Q2Wa/0Nlmv8hRXX/Q2Wa/yJDdf9DZZr/IkV3/yFFdf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiRXf/IkN1/yJDdf9FZpf/IEN1/0Vml/8iQ3X/IkV3/yJFd/8iRXf/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIkV3/yJFd/8iRXf/IkV3/yJFd/8iRXf/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
            BACKGROUND: "Qk02EAAAAAAAADYAAAAoAAAAIAAAAOD///8BACAAAAAAAAAQAAATCwAAEwsAAAAAAAAAAAAAQURB/0lISf9BREH/amxq/0FEQf9qaGr/QURB/2psav9BREH/SUhJ/0lISf9qaGr/QURB/0lISf9JSEn/SUhJ/0lISf9JSEn/QURB/2poav9qaGr/YmRi/0lISf9JSEn/SUhJ/0FEQf9qbGr/YmRi/0lISf9JSEn/QURB/0lISf9qbGr/QURB/2psav9BREH/amhq/0FEQf9qbGr/YmRi/2poav9BREH/QURB/0FEQf9qaGr/QURB/2JkYv9BREH/SUhJ/2JkYv9JSEn/QURB/2poav9BREH/SUhJ/2JkYv9BREH/amxq/0FAQf9qaGr/QURB/2JkYv9qbGr/YmRi/0lISf9JSEn/QURB/2psav9JSEn/amhq/2poav9JSEn/SUhJ/0FEQf9JSEn/amhq/0lISf9qaGr/amxq/2poav9qaGr/amhq/2poav9JSEn/SUhJ/0lESf9qbGr/QURB/2poav9BREH/amxq/2poav9qaGr/SUhJ/2poav9JSEn/amxq/0FEQf9qaGr/QURB/2psav9BREH/SUhJ/0FEQf9qbGr/QUhB/0FIQf9BREH/amxq/0FEQf9JSEn/QURB/0FEQf9JSEn/QURB/0lISf9BREH/QURB/0FEQf9qaGr/SUhJ/2poav9qaGr/amhq/2JkYv9qaGr/SUhJ/2poav9DQ0P/Q0ND/0NDQ/9DQ0P/Q0ND/0NDQ/9DQ0P/ZWVl/0NDQ/9lZWX/Q0ND/0NDQ/9DQ0P/Q0ND/0NDQ/9DQ0P/Q0ND/0NDQ/9DQ0P/Q0ND/0NDQ/9lZWX/Q0ND/2VlZf9DQ0P/Q0ND/0NDQ/9DQ0P/Q0ND/0NDQ/9DQ0P/ZWVl/0NDQ/9DQ0P/ZWVl/0NDQ/9lZWX/Q0ND/2VlZf9DQ0P/ZWVl/0NDQ/9DQ0P/Q0ND/0NDQ/9DQ0P/ZWVl/0NDQ/9lZWX/ZWVl/0NDQ/9DQ0P/Q0ND/0NDQ/9DQ0P/Q0ND/0NDQ/9DQ0P/ZWVl/0NDQ/9lZWX/Q0ND/0NDQ/9DQ0P/Q0ND/2VlZf9DQ0P/ZWVl/2VlZf9DQ0P/Q0ND/2VlZf9DQ0P/ZWVl/0NDQ/9DQ0P/Q0ND/2VlZf9DQ0P/ZWVl/2VlZf9lZWX/ZWVl/0NDQ/9DQ0P/ZWVl/0NDQ/9DQ0P/Q0ND/2VlZf9DQ0P/ZWVl/2VlZf9lZWX/ZWVl/0NDQ/9DQ0P/Q0ND/2VlZf9lZWX/ZWVl/2VlZf9DQ0P/Q0ND/2VlZf9lZWX/Q0ND/0NDQ/9lZWX/Q0ND/2VlZf9lZWX/ZWVl/2VlZf9lZWX/Q0ND/2VlZf9DQ0P/ZWVl/0NDQ/9lZWX/Q0ND/2VlZf9lZWX/ZWVl/2VlZf9lZWX/Q0ND/0NDQ/9lZWX/Q0ND/2VlZf9lZWX/ZWVl/0NDQ/9lZWX/ZWVl/2VlZf9DQ0P/ZWVl/0NDQ/9lZWX/ZWVl/2VlZf9lZWX/ZWVl/2VlZf9DQ0P/Q0ND/2VlZf9DQ0P/Q0ND/0NDQ/9lZWX/Q0ND/2VlZf9lZWX/ZWVl/2VlZf9DQ0P/ZWVl/0NDQ/9lZWX/Q0ND/2VlZf9lZWX/Q0ND/2VlZf9lZWX/ZWVl/0NDQ/9DQ0P/ZWVl/0NDQ/9lZWX/ZWVl/2VlZf9lZWX/Q0ND/0NDQ/9lZWX/Q0ND/2VlZf9DQ0P/ZWVl/0NDQ/9lZWX/ZWVl/2VlZf9lZWX/Q0ND/0NDQ/9lZWX/Q0ND/0NDQ/9lZWX/Q0ND/2VlZf9DQ0P/Q0ND/2VlZf9DQ0P/Q0ND/0NDQ/9DQ0P/ZWVl/0NDQ/9lZWX/ZWVl/0NDQ/9DQ0P/Q0ND/2VlZf9lZWX/Q0ND/0NDQ/9DQ0P/ZWVl/0NDQ/9lZWX/ZWVl/0NDQ/9DQ0P/ZWVl/2VlZf9lZWX/Q0ND/0NDQ/9DQ0P/Q0ND/2VlZf9DQ0P/Q0ND/0NDQ/9lZWX/Q0ND/2VlZf9DQ0P/Q0ND/0NDQ/9DQ0P/Q0ND/0NDQ/9lZWX/ZWVl/2VlZf9lZWX/Q0ND/0NDQ/9DQ0P/Q0ND/0NDQ/9DQ0P/Q0ND/0NDQ/9lZWX/ZWVl/0NDQ/9DQ0P/ZWVl/0NDQ/9lZWX/Q0ND/2VlZf9lZWX/ZWVl/0NDQ/9lZWX/Q0ND/0NDQ/9DQ0P/ZWVl/0NDQ/9lZWX/ZWVl/2VlZf9lZWX/ZWVl/0NDQ/9DQ0P/Q0ND/0NDQ/9lZWX/ZWVl/0NDQ/9lZWX/Q0ND/0NDQ/9DQ0P/Q0ND/2VlZf9DQ0P/ZWVl/0NDQ/9lZWX/ZWVl/2VlZf9lZWX/ZWVl/0NDQ/9DQ0P/Q0ND/2VlZf9DQ0P/ZWVl/2VlZf9lZWX/ZWVl/2VlZf9DQ0P/ZWVl/0NDQ/9DQ0P/ZWVl/2VlZf9lZWX/ZWVl/0NDQ/9lZWX/Q0ND/0NDQ/9lZWX/Q0ND/2VlZf9DQ0P/ZWVl/2VlZf9lZWX/ZWVl/2VlZf9DQ0P/ZWVl/0NDQ/9DQ0P/Q0ND/2VlZf9DQ0P/ZWVl/2VlZf9lZWX/Q0ND/2VlZf9DQ0P/ZWVl/0NDQ/9lZWX/ZWVl/2VlZf9DQ0P/ZWVl/0NDQ/9DQ0P/Q0ND/0NDQ/9DQ0P/Q0ND/2VlZf9DQ0P/ZWVl/2VlZf9lZWX/ZWVl/0NDQ/9DQ0P/ZWVl/0NDQ/9DQ0P/Q0ND/2VlZf9DQ0P/ZWVl/0NDQ/9lZWX/Q0ND/2VlZf9DQ0P/Q0ND/0NDQ/9lZWX/Q0ND/2VlZf9DQ0P/Q0ND/0NDQ/9DQ0P/Q0ND/0NDQ/9DQ0P/Q0ND/0NDQ/9DQ0P/Q0ND/0NDQ/9DQ0P/Q0ND/2VlZf9DQ0P/Q0ND/0NDQ/9DQ0P/Q0ND/0NDQ/9DQ0P/Q0ND/0NDQ/9DQ0P/Q0ND/0NDQ/9DQ0P/Q0ND/0NDQ/9DQ0P/Q0ND/0NDQ/9DQ0P/ZWVl/0NDQ/9DQ0P/ZWVl/0NDQ/9DQ0P/Q0ND/0NDQ/9DQ0P/ZWVl/0NDQ/9lZWX/Q0ND/0NDQ/9DQ0P/ZWVl/0NDQ/9DQ0P/Q0ND/2VlZf9DQ0P/ZWVl/2VlZf9lZWX/ZWVl/2VlZf9DQ0P/Q0ND/0NDQ/9lZWX/Q0ND/2VlZf9DQ0P/Q0ND/2VlZf9DQ0P/ZWVl/2VlZf9lZWX/Q0ND/2VlZf9DQ0P/ZWVl/2VlZf9lZWX/Q0ND/2VlZf9DQ0P/ZWVl/0NDQ/9lZWX/Q0ND/2VlZf9lZWX/ZWVl/2VlZf9lZWX/Q0ND/2VlZf9DQ0P/ZWVl/0NDQ/9lZWX/Q0ND/2VlZf9DQ0P/Q0ND/2VlZf9lZWX/ZWVl/0NDQ/9lZWX/Q0ND/2VlZf9lZWX/ZWVl/2VlZf9DQ0P/Q0ND/2VlZf9DQ0P/Q0ND/0NDQ/9lZWX/Q0ND/2VlZf9lZWX/ZWVl/2VlZf9lZWX/Q0ND/0NDQ/9DQ0P/ZWVl/0NDQ/9lZWX/ZWVl/0NDQ/9lZWX/ZWVl/2VlZf9lZWX/ZWVl/0NDQ/9lZWX/Q0ND/2VlZf9lZWX/ZWVl/0NDQ/9lZWX/Q0ND/2VlZf9lZWX/Q0ND/0NDQ/9lZWX/ZWVl/2VlZf9lZWX/ZWVl/0NDQ/9lZWX/Q0ND/2VlZf9DQ0P/ZWVl/2VlZf9lZWX/Q0ND/0NDQ/9lZWX/ZWVl/0NDQ/9DQ0P/Q0ND/0NDQ/9lZWX/ZWVl/2VlZf9DQ0P/Q0ND/0NDQ/9lZWX/ZWVl/2VlZf9lZWX/Q0ND/0NDQ/9lZWX/ZWVl/2VlZf9DQ0P/ZWVl/0NDQ/9DQ0P/Q0ND/2VlZf9DQ0P/ZWVl/2VlZf9DQ0P/Q0ND/0NDQ/9DQ0P/Q0ND/2VlZf9DQ0P/Q0ND/0NDQ/9DQ0P/Q0ND/0NDQ/9DQ0P/ZWVl/0NDQ/9lZWX/ZWVl/2VlZf9DQ0P/Q0ND/0NDQ/9DQ0P/Q0ND/0NDQ/9DQ0P/Q0ND/0NDQ/9DQ0P/Q0ND/0NDQ/9DQ0P/Q0ND/0NDQ/9DQ0P/ZWVl/0NDQ/9lZWX/Q0ND/2VlZf9lZWX/ZWVl/0NDQ/9DQ0P/Q0ND/2VlZf9DQ0P/ZWVl/2VlZf9lZWX/ZWVl/0NDQ/9lZWX/ZWVl/2VlZf9DQ0P/Q0ND/2VlZf9DQ0P/ZWVl/0NDQ/9lZWX/Q0ND/0NDQ/9DQ0P/Q0ND/0NDQ/9DQ0P/ZWVl/0NDQ/9lZWX/ZWVl/2VlZf9lZWX/Q0ND/0NDQ/9lZWX/Q0ND/2VlZf9DQ0P/ZWVl/2VlZf9DQ0P/Q0ND/2VlZf9lZWX/Q0ND/0NDQ/9lZWX/Q0ND/2VlZf9DQ0P/ZWVl/2VlZf9lZWX/Q0ND/2VlZf9DQ0P/Q0ND/0NDQ/9DQ0P/ZWVl/0NDQ/9DQ0P/Q0ND/0NDQ/9DQ0P/Q0ND/0NDQ/9lZWX/Q0ND/0NDQ/9DQ0P/Q0ND/0NDQ/9DQ0P/Q0ND/0NDQ/9DQ0P/Q0ND/0NDQ/9DQ0P/Q0ND/2VlZf9lZWX/ZWVl/0NDQ/9DQ0P/Q0ND/0NDQ/9DQ0P/Q0ND/0NDQ/9DQ0P/Q0ND/0NDQ/9lZWX/Q0ND/2VlZf9lZWX/Q0ND/0NDQ/9DQ0P/Q0ND/2VlZf9DQ0P/ZWVl/2VlZf9lZWX/Q0ND/0NDQ/9DQ0P/ZWVl/0NDQ/9DQ0P/ZWVl/2VlZf9lZWX/ZWVl/0NDQ/9DQ0P/Q0ND/0NDQ/9lZWX/ZWVl/0NDQ/9DQ0P/ZWVl/0NDQ/9lZWX/ZWVl/2VlZf9lZWX/Q0ND/0NDQ/9lZWX/Q0ND/2VlZf9lZWX/ZWVl/0NDQ/9lZWX/Q0ND/2VlZf9DQ0P/ZWVl/0NDQ/9lZWX/ZWVl/2VlZf9DQ0P/ZWVl/0NDQ/9DQ0P/ZWVl/2VlZf9lZWX/Q0ND/2VlZf9DQ0P/ZWVl/2VlZf9lZWX/ZWVl/2VlZf9DQ0P/ZWVl/0NDQ/9lZWX/ZWVl/2VlZf9lZWX/ZWVl/0NDQ/9DQ0P/Q0ND/2VlZf9DQ0P/Q0ND/0NDQ/9lZWX/ZWVl/2VlZf9DQ0P/Q0ND/0NDQ/9lZWX/ZWVl/2VlZf9DQ0P/Q0ND/2VlZf9DQ0P/ZWVl/2VlZf9lZWX/ZWVl/0NDQ/9DQ0P/ZWVl/0NDQ/9lZWX/ZWVl/2VlZf9DQ0P/ZWVl/0NDQ/9lZWX/Q0ND/2VlZf9DQ0P/ZWVl/0NDQ/9lZWX/Q0ND/2VlZf9DQ0P/Q0ND/0NDQ/9lZWX/ZWVl/0NDQ/9DQ0P/Q0ND/2VlZf9DQ0P/ZWVl/2VlZf9DQ0P/Q0ND/2VlZf9DQ0P/Q0ND/0NDQ/9lZWX/Q0ND/2VlZf9lZWX/Q0ND/0NDQ/9lZWX/Q0ND/0NDQ/9DQ0P/ZWVl/0NDQ/9lZWX/Q0ND/0NDQ/9lZWX/Q0ND/2VlZf9lZWX/ZWVl/0NDQ/9DQ0P/Q0ND/2VlZf9DQ0P/Q0ND/0NDQ/9lZWX/ZWVl/2VlZf9DQ0P/Q0ND/0NDQ/9DQ0P/ZWVl/2VlZf9lZWX/Q0ND/0NDQ/9DQ0P/Q0ND/0NDQ/9DQ0P/Q0ND/0NDQ/9DQ0P/Q0ND/w==",
            SLM_GREEN : "Qk02EAAAAAAAADYAAAAoAAAAIAAAAOD///8BACAAAAAAAAAQAADEDgAAxA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACqzKr/qsyq/6rMqv+qzKr/qsyq/6rMqv+qzKr/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKrMqv+qzKr/qsyq/8zuzP/M7sz/zO7M/8zuzP/M7sz/zO7M/6rMqv+qzKr/qsyq/6rMqv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACqzKr/qsyq/8zuzP/M7sz/zO7M/8zuzP/M7sz/zO7M/8zuzP/M7sz/zO7M/6rMqv/M7sz/qsyq/6rMqv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqsyq/6rMqv/M7sz/zO7M/8zuzP/M7sz/zO7M/8zuzP/M7sz/zO7M/8zuzP/M7sz/zO7M/6rMqv/M7sz/qsyq/6rMqv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACqzKr/zO7M/8zuzP/MzMz/zMzM/8zMzP/M7sz/zO7M/8zuzP/M7sz/zO7M/8zMzP/MzMz/zMzM/6rMqv/M7sz/qsyq/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqsyq/6rMqv/M7sz/zMzM/////////////////8zMzP/M7sz/zO7M/8zuzP/MzMz/////////////////zMzM/6rMqv+qzKr/qsyq/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACqzKr/zO7M/8zMzP///////////0RERP9ERET//////8zMzP/M7sz/zMzM//////9ERET/RERE////////////zMzM/6rMqv+qzKr/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKrMqv/M7sz/zMzM////////////RERE/8zMzP//////zMzM/8zuzP/MzMz//////8zMzP9ERET////////////MzMz/zO7M/6rMqv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqsyq/8zuzP/MzMz///////////9ERET/RERE///////MzMz/zO7M/8zMzP//////RERE/0RERP///////////8zMzP+qzKr/qsyq/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACqzKr/qsyq/8zuzP/MzMz/////////////////zMzM/8zuzP/M7sz/zO7M/8zMzP/////////////////MzMz/qsyq/6rMqv+qzKr/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACqzKr/zO7M/8zuzP/MzMz/zMzM/8zMzP/M7sz/zO7M/8zuzP/M7sz/zO7M/8zMzP/MzMz/zMzM/6rMqv/M7sz/qsyq/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKrMqv+qzKr/zO7M/8zuzP/M7sz/zO7M/8zuzP/M7sz/zO7M/8zuzP/M7sz/zO7M/8zuzP+qzKr/zO7M/6rMqv+qzKr/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKrMqv+qzKr/zO7M/8zuzP/M7sz/zO7M/8zuzP/M7sz/zO7M/6rMqv/M7sz/qsyq/8zuzP+qzKr/qsyq/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKrMqv+qzKr/qsyq/8zuzP/M7sz/qsyq/8zuzP+qzKr/zO7M/6rMqv+qzKr/qsyq/6rMqv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqsyq/6rMqv+qzKr/qsyq/6rMqv+qzKr/qsyq/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
        }
    },
    CANVAS : {
        EMPTY_CANVAS: {},
        MAP_CANVAS: {},
        GUI_CANVAS: {},
        BACK_CANVAS: {},
        LEFT_STATUS_CANVAS: {},
        RIGHT_STATUS_CANVAS: {},
        MSG_CANVAS: {},
        ITEM_CANVAS: {},
        DIALOG_CANVAS: {}
    }
    ,
    CACHE : {
        BMD : {}
    },
    KEY_BLOCKED : false,
    MOUSE_BLOCKED : false,
    SPECIAL : {
        YES_CALLBACK : function () {
            trace("yes");
        },
        NO_CALLBACK : function () {
            trace("no");
        }
    }
};

function initMap() {
    Global.MAP.length = Global.MAP_SIZE.x;

    for (var i = 0; i < Global.MAP.length; i++) {
        Global.MAP[i] = [];
        Global.MAP[i].length = Global.MAP_SIZE.y;
    }

    for (var i = 0; i < Global.MAP_SIZE.x; i++) {
        for (var j = 0; j < Global.MAP_SIZE.y; j++) {
            Global.MAP[i][j]= {};
            Global.MAP[i][j].objects = [];
            var obj =  createBMPObj(32, 32, "BACKGROUND", Global.TYPE.BACKGROUND, 0, Global.MAP_SCALE, Global.CANVAS.MAP_CANVAS);

            obj.shape.x = i * Global.BLOCK_SIZE.x;
            obj.shape.y = j * Global.BLOCK_SIZE.y;
            obj.x = i;
            obj.y = j;
            obj.onClicked = function() {

                var xx = this.x;
                var yy = this.y;

                if (Mouse.target != null && Global.MAP[xx][yy].objects.length <= 1) {
                    var place_obj = placeObj(Mouse.target.bmp_type, Mouse.target.type, xx, yy);
                    place_obj.rigid = true;
                    if (place_obj.type == Global.TYPE.NPC_TRADE) {
                        place_obj.onCollision = function (obj, dir) {
                            if (obj.type == Global.TYPE.PLAYER) {
                                createDialogStrip([["1",  function () {
                                    Global.PLAYER.status.HP -= 10;
                                    refreshPlayerStatus();
                                }], ["2", function () {
                                    Global.PLAYER.status.HP += 10;
                                    refreshPlayerStatus();
                                }], ["3", function () {
                                    Global.PLAYER.status.HP -= 50;
                                    refreshPlayerStatus();
                                }]]);
                            }
                        };
                    } else if (place_obj.type == Global.TYPE.KEY_YELLOW) {
                        place_obj.onCollision = function (obj, dir) {
                            if (obj.type == Global.TYPE.PLAYER) {
                                obj.items.push({
                                    bmp_type: place_obj.bmp_type,
                                    type : place_obj.type
                                });
                                refreshPlayerItems();
                                removeObj(place_obj);
                            }
                        };
                    }

                } else if (Global.MAP[xx][yy].objects.length > 1) {
                    removeObj(Global.MAP[xx][yy].objects[Global.MAP[xx][yy].objects.length - 1]);
                }
            };
            obj.onEntered = function() {
                var g = $.createShape({lifeTime:0,x:(this.absPos()).x,y:(this.absPos()).y});
                g.graphics.moveTo(0, 0);
                g.graphics.lineStyle(2, 0xFF4040, 1, false);
                g.graphics.lineTo(Global.BLOCK_SIZE.x, 0);
                g.graphics.lineTo(Global.BLOCK_SIZE.x, Global.BLOCK_SIZE.y);
                g.graphics.lineTo(0, Global.BLOCK_SIZE.y);
                g.graphics.lineTo(0, 0);
                this.g = g;
            };
            obj.onLeaved = function() {
                this.g.graphics.clear();
                this.g = {};
            };
            Global.MAP[i][j].objects.push(obj);
        }
    }
}

function initPlayer() {
    Global.PLAYER = createBMPObj(32, 32, "WARRIOR_BLUE", Global.TYPE.PLAYER, 0, Global.MAP_SCALE, Global.CANVAS.MAP_CANVAS);
    Global.PLAYER.shape.x = Global.BLOCK_SIZE.x * 5;
    Global.PLAYER.shape.y = Global.BLOCK_SIZE.y * 5;
    Global.PLAYER.x = 5;
    Global.PLAYER.y = 5;
    Global.PLAYER.status = clone(Global.DATA.PLAYER);
    /*Global.MAP[5][5].objects.push(Global.PLAYER);*/

    Global.PLAYER.items = [];
    Global.PLAYER.moveUp = function () {
        if (this.y > 0) {
            this.y -= 1;
            this.shape.y = Global.BLOCK_SIZE.y * this.y;
        }
    };

    Global.PLAYER.moveDown = function () {
        if (this.y < Global.MAP_SIZE.y - 1) {
            this.y += 1;
            this.shape.y = Global.BLOCK_SIZE.y * this.y;
        }
    };

    Global.PLAYER.moveLeft = function () {
        if (this.x > 0) {
            this.x -= 1;
            this.shape.x = Global.BLOCK_SIZE.x * this.x;
        }
    };

    Global.PLAYER.moveRight = function () {
        if (this.x < Global.MAP_SIZE.x - 1) {
            this.x += 1;
            this.shape.x = Global.BLOCK_SIZE.x * this.x;
        }
    };

    Global.PLAYER.rigid = true;
    Global.PLAYER.onCollision = function (obj, dir) {
        /* TODO: check if it is monster */
        if (obj.type == Global.TYPE.SLM_GREEN) {
            enterBattle(this, obj, true);
        }

        /*trace(dir);*/
    };
    Global.PLAYER.onBattleWin = function (obj) {
        log("你赢了");
        removeObj(obj);
    };
}

function placeObj(bmp_type, type, x, y) {
    var obj = createBMPObj(32, 32, bmp_type, type, 0, Global.MAP_SCALE, Global.CANVAS.MAP_CANVAS);
    obj.shape.x = Global.BLOCK_SIZE.x * x;
    obj.shape.y = Global.BLOCK_SIZE.y * y;
    obj.x = x;
    obj.y = y;
    obj.status = clone(Global.DATA[type]);
    Global.MAP[x][y].objects.push(obj);
    return obj;
}

function removeObj(obj) {
    var x = parseInt(obj.x);
    var y = parseInt(obj.y);
    obj.shape.alpha = 0;
    var index = Global.MAP[x][y].objects.indexOf(obj);
    Global.MAP[x][y].objects.splice(index, 1);
    obj.Destroy();
}

function keyDown(key) {
    if (Global.KEY_BLOCKED) return;
    if (Global.PLAYER != {}) {
        if (key == 87 || key == 38) {
            Global.PLAYER.moveUp();
        } else if (key == 83 || key == 40) {
            Global.PLAYER.moveDown();
        } else if (key == 65 || key == 37) {
            Global.PLAYER.moveLeft();
        } else if (key == 68 || key == 39) {
            Global.PLAYER.moveRight();
        }
    }
}

function initListener() {
    /* $.frameRate = 30; */
    $.root.mouseEnabled = true;

    $.root.addEventListener("enterFrame", function () {
        EventManager.EnterFrame();
    });

    $.root.addEventListener("mouseMove", function (e) {
        EventManager.MouseMove(e);
    });
    $.root.addEventListener("mouseUp", function (e) {
        EventManager.MouseUp(e);
    });
}

function init() {

    ScriptManager.clearTimer();
    ScriptManager.clearEl();
    ScriptManager.clearTrigger();

    Player.keyTrigger(function(key){
        keyDown(key);
    }, 1<<31 -1);



    /*Global.CACHE.BMD.length = Global.BLOCK_TYPE.CNT;*/
    Global.BLOCK_SIZE.x = Global.BLOCK_SIZE.y = Math.floor(Math.min(Player.width / Global.MAP_SIZE.x, Player.height / Global.MAP_SIZE.y));
    Global.MAP_SCALE = Global.BLOCK_SIZE.x / 32;


    /*Global.CANVAS.EMPTY_CANVAS = createCanvas({
       x: 0,
       y: 0,
       lifeTime: 0
    });
    Player.keyTrigger(function(key){
       keyUp(key);
    },INT_MAX,true);*/

}

function log(msg) {
    (Global.CANVAS.MSG_CANVAS.getChildByName("msg")).text = msg;
}

/*************************************** diaglog functions ****************************/
function showPanel() {
    var textfield = Global.CANVAS.DIALOG_CANVAS.getChildByName('msg');
    textfield.text = "";
    Global.CANVAS.DIALOG_CANVAS.alpha = 1.;
}

function hidePanel() {
    var textfield = Global.CANVAS.DIALOG_CANVAS.getChildByName('msg');
    textfield.text = "";
    Global.CANVAS.DIALOG_CANVAS.alpha = 0.;
}

function dialog(text, yes_callback, no_callback) {
    var textfield = Global.CANVAS.DIALOG_CANVAS.getChildByName('msg');
    textfield.text = text;
    if (textfield.width > maxwidth)
    {
        textfield.multiline = true;
        textfield.wordWrap = true;
        textfield.width = maxwidth;
    }
    /*ScriptManager.clearEl();*/
    var yes_but = Global.CANVAS.DIALOG_CANVAS.getChildByName('yes_but');
    if (yes_callback != null) {
        yes_but.alpha = 1.;
        Global.SPECIAL.YES_CALLBACK = yes_callback;
    } else {
        yes_but.alpha = 0;
        Global.SPECIAL.YES_CALLBACK = function () {};
    }
    var no_but = Global.CANVAS.DIALOG_CANVAS.getChildByName('no_but');
    if (no_callback != null) {
        no_but.alpha = 1.;
        Global.SPECIAL.NO_CALLBACK = no_callback;
    } else {
        no_but.alpha = 0;
        Global.SPECIAL.NO_CALLBACK = function () {};
    }
}

function createDialogRecur(arr) {
    if (arr.length == 0) {
        hidePanel();
        Global.KEY_BLOCKED = false;
        return;
    }
    var d = arr[0];
    arr.splice(0, 1);
    var yes_call = d.length > 1 ? function () {
        (d[1])();
        createDialogRecur(arr);
    } : function () {
        createDialogRecur(arr);
    };
    var no_call = d.length > 2 ?  function () {
        (d[2])();
        createDialogRecur(arr);
    } : function () {
        createDialogRecur(arr);
    };
    dialog(d[0], yes_call, no_call);
}

function createDialogStrip(arr) {
    Global.KEY_BLOCKED = true;
    showPanel();
    createDialogRecur(arr);
}
/*************************************** diaglog functions end***************************/

/************************************** item functions begin ******************************/

function refreshPlayerItems() {
    /* clear current items */

    var objs = ObjPool.objects;
    var garbbage = [];
    for (var i = 0; i < objs.length; ++i) {
        var o = objs[i];
        if (o.parent == Global.CANVAS.ITEM_CANVAS) {
            garbbage.push(o);
        }
    }
    for (var i = 0; i < garbbage.length; ++i) {
        garbbage[i].Destroy();
    }

    while (Global.CANVAS.ITEM_CANVAS.numChildren > 0) {
        Global.CANVAS.ITEM_CANVAS.removeChildAt(0);
    }

    var player = Global.PLAYER;
    var x_offset = 20, y_offset = 0;
    for (var i = 0;  i < player.items.length; i++) {
        var item = player.items[i];
        var obj = createBMPObj(32, 32, item.bmp_type, item.type, 0, 0.6 * Global.MAP_SCALE, Global.CANVAS.ITEM_CANVAS);
        obj.shape.x = x_offset;
        obj.shape.y = y_offset;
        if (item.hasOwnProperty("onClicked")) {
            obj.onClicked = item.onClicked;
        }
        x_offset += 24;
        if (i % 4 == 0 && i != 0) {
            x_offset = 20;
            y_offset += 24;
        }
    }
}

/************************************** item functions end ******************************/

function editInit() {
    Global.CANVAS.MAP_CANVAS = createCanvas({
        x: Player.width/2 - Global.MAP_SIZE.x/2 * Global.BLOCK_SIZE.x,
        y: Player.height/2 - Global.MAP_SIZE.y/2 * Global.BLOCK_SIZE.y,
        lifeTime: 0
    });

    Global.CANVAS.GUI_CANVAS = createCanvas({
        x: Player.width/2 + Global.MAP_SIZE.x/2 * Global.BLOCK_SIZE.x,
        y: Player.height/2 - Global.MAP_SIZE.y/2 * Global.BLOCK_SIZE.y,
        lifeTime: 0
    });

    var bmp = createBMPObj(32, 32, "SLM_GREEN", Global.TYPE.SLM_GREEN, 0, Global.MAP_SCALE, Global.CANVAS.GUI_CANVAS);
    bmp.onClicked = function() {
        if (Mouse.target != null && Mouse.target.type == this.type) {
            criptManager.popEl(Mouse.target.shape);
            Mouse.Detach();
        } else {
            var a = createBMPObj(32, 32, this.bmp_type, this.type, 0, Global.MAP_SCALE, 0);
            a.shape.x = (this.absPos()).x;
            a.shape.y = (this.absPos()).y;
            a.shape.alpha = 0.5;
            Mouse.Attach(a);
        }
    };

    var npc = createBMPObj(32, 32, "NPC001", Global.TYPE.NPC_TRADE, 0, Global.MAP_SCALE, Global.CANVAS.GUI_CANVAS);
    npc.shape.x = 50;
    npc.onClicked = function() {
        if (Mouse.target != null && Mouse.target.type == this.type) {
            ScriptManager.popEl(Mouse.target.shape);
            Mouse.Detach();
        } else {
            var a = createBMPObj(32, 32, this.bmp_type, this.type, 0, Global.MAP_SCALE, 0);
            a.shape.x = (this.absPos()).x;
            a.shape.y = (this.absPos()).y;
            a.shape.alpha = 0.5;
            Mouse.Attach(a);
        }
    };

    var key = createBMPObj(32, 32, "KEY_YELLOW", Global.TYPE.KEY_YELLOW, 0, Global.MAP_SCALE, Global.CANVAS.GUI_CANVAS);
    key.shape.x = 100;
    key.onClicked = function() {
        if (Mouse.target != null && Mouse.target.type == this.type) {
            ScriptManager.popEl(Mouse.target.shape);
            Mouse.Detach();
        } else {
            var a = createBMPObj(32, 32, this.bmp_type, this.type, 0, Global.MAP_SCALE, 0);
            a.shape.x = (this.absPos()).x;
            a.shape.y = (this.absPos()).y;
            a.shape.alpha = 0.5;
            Mouse.Attach(a);
        }
    };

    $.createButton({
        x:0,
        y:300,
        parent:Global.CANVAS.GUI_CANVAS,
        text:"编辑",
        onclick:function(){
            Global.KEY_BLOCKED = true;
            Global.MOUSE_BLOCKED = false;
        },
        lifeTime: 0
    });
    $.createButton({
        x:0,
        y:400,
        parent:Global.CANVAS.GUI_CANVAS,
        text:"测试",
        onclick:function(){
            Global.KEY_BLOCKED = false;
            Global.MOUSE_BLOCKED = true;
        },
        lifeTime: 0
    });

}

function refreshPlayerStatus() {
    (Global.CANVAS.LEFT_STATUS_CANVAS.getChildByName("hp")).text = Global.PLAYER.status.HP + "";
    (Global.CANVAS.LEFT_STATUS_CANVAS.getChildByName("atk")).text = Global.PLAYER.status.ATK + "";
    (Global.CANVAS.LEFT_STATUS_CANVAS.getChildByName("def")).text = Global.PLAYER.status.DEF + "";
}

function battleFrame(player, monster, turn) {
    if (!turn) {
        player.status.HP -= monster.status.ATK;
        /*trace(player.status.HP);*/
        (Global.CANVAS.LEFT_STATUS_CANVAS.getChildByName("hp")).text = player.status.HP;
    } else {
        monster.status.HP -= player.status.ATK;
        /*trace(monster.status.HP);*/
        (Global.CANVAS.RIGHT_STATUS_CANVAS.getChildByName("hp")).text = monster.status.HP;
    }

    turn = !turn;
    if (player.status.HP <= 0) {
        Global.KEY_BLOCKED = false;
        if (player.hasOwnProperty("onBattleLose")) {
            player.onBattleLose(monster);
        }
        if (monster.hasOwnProperty("onBattleWin")) {
            monster.onBattleWin(player);
        }
    } else if (monster.status.HP <= 0) {
        Global.KEY_BLOCKED = false;
        if (player.hasOwnProperty("onBattleWin")) {
            player.onBattleWin(monster);
        }
        if (monster.hasOwnProperty("onBattleLose")) {
            monster.onBattleLose(player);
        }
    } else {
        timer(function() {
            battleFrame(player, monster, turn);
        }, 200);
    }
}

function enterBattle(player, monster, active) {
    /*reset monster GUI*/
    (Global.CANVAS.RIGHT_STATUS_CANVAS.getChildByName("hp")).text = monster.status.HP + "";
    (Global.CANVAS.RIGHT_STATUS_CANVAS.getChildByName("atk")).text = monster.status.ATK + "";
    (Global.CANVAS.RIGHT_STATUS_CANVAS.getChildByName("def")).text = monster.status.DEF + "";

    Global.KEY_BLOCKED = true;
    timer(function() {
        battleFrame(player, monster, active);
    }, 300);
}

function GUIInit() {
    createText("勇士信息", {x : 30, y : 60, parent : Global.CANVAS.LEFT_STATUS_CANVAS});
    createText("生命", {x : 30, y : 100, parent : Global.CANVAS.LEFT_STATUS_CANVAS});
    createText("攻击", {x : 30, y : 140, parent : Global.CANVAS.LEFT_STATUS_CANVAS});
    createText("防御", {x : 30, y : 180, parent : Global.CANVAS.LEFT_STATUS_CANVAS});
    (createText(Global.PLAYER.status.HP + "", {x : 80, y : 100, parent : Global.CANVAS.LEFT_STATUS_CANVAS})).name = "hp";
    (createText(Global.PLAYER.status.ATK + "", {x : 80, y : 140, parent : Global.CANVAS.LEFT_STATUS_CANVAS})).name = "atk";
    (createText(Global.PLAYER.status.DEF + "", {x : 80, y : 180, parent : Global.CANVAS.LEFT_STATUS_CANVAS})).name = "def";


    createText("怪物信息", {x : 30, y : 60, parent : Global.CANVAS.RIGHT_STATUS_CANVAS});
    createText("生命", {x : 30, y : 100, parent : Global.CANVAS.RIGHT_STATUS_CANVAS});
    createText("攻击", {x : 30, y : 140, parent : Global.CANVAS.RIGHT_STATUS_CANVAS});
    createText("防御", {x : 30, y : 180, parent : Global.CANVAS.RIGHT_STATUS_CANVAS});
    (createText("0", {x : 80, y : 100, parent : Global.CANVAS.RIGHT_STATUS_CANVAS})).name = "hp";
    (createText("0", {x : 80, y : 140, parent : Global.CANVAS.RIGHT_STATUS_CANVAS})).name = "atk";
    (createText("0", {x : 80, y : 180, parent : Global.CANVAS.RIGHT_STATUS_CANVAS})).name = "def";

    /* item panel */
    Global.CANVAS.ITEM_CANVAS = createCanvas({
        x: 0,
        y: Player.height / 2,
        lifeTime: 0
    });
}

function gameInit() {
    Global.CANVAS.MAP_CANVAS = createCanvas({
        x: Player.width/2 - Global.MAP_SIZE.x/2 * Global.BLOCK_SIZE.x,
        y: Player.height/2 - Global.MAP_SIZE.y/2 * Global.BLOCK_SIZE.y,
        lifeTime: 0
    });

    Global.CANVAS.LEFT_STATUS_CANVAS = createCanvas({
        x: 0,
        y: 0,
        lifeTime: 0
    });

    Global.CANVAS.MSG_CANVAS = createCanvas({
        x: 0,
        y: (Global.MAP_SIZE.y - 1) * Global.BLOCK_SIZE.y,
        lifeTime: 0
    });

    (createText("", {x : 10, y : 15, parent : Global.CANVAS.MSG_CANVAS})).name = "msg";

    var margin = (Player.width - Global.MAP_SIZE.x * Global.BLOCK_SIZE.x) / 2;
    Global.CANVAS.DIALOG_CANVAS = createCanvas({
        x: margin + Global.MAP_SIZE.x / 4 * Global.BLOCK_SIZE.x,
        y: Global.MAP_SIZE.y / 4 * Global.BLOCK_SIZE.y,
        lifeTime: 0
    });

    (createRectangle(Global.CANVAS.DIALOG_CANVAS, 0x333333, Global.MAP_SIZE.x / 2 * Global.BLOCK_SIZE.x, Global.MAP_SIZE.y / 2 * Global.BLOCK_SIZE.y));
    (createText("", {x : 10, y : 15, parent : Global.CANVAS.DIALOG_CANVAS})).name = 'msg';

    ($.createButton({
        x: Global.CANVAS.DIALOG_CANVAS.width - 80,
        y: Global.CANVAS.DIALOG_CANVAS.height - 80,
        parent:Global.CANVAS.DIALOG_CANVAS,
        text:"好",
        onclick: function () {
            Global.SPECIAL.YES_CALLBACK();
        },
        lifeTime: 0
    })).name = 'yes_but';

    ($.createButton({
        x: Global.CANVAS.DIALOG_CANVAS.width - 80,
        y: Global.CANVAS.DIALOG_CANVAS.height - 40,
        parent:Global.CANVAS.DIALOG_CANVAS,
        text:"不好",
        onclick: function () {
            Global.SPECIAL.NO_CALLBACK();
        },
        lifeTime: 0
    })).name = 'no_but';

    hidePanel();

    /*Global.CANVAS.DIALOG_CANVAS.alpha = 0;*/


    Global.CANVAS.RIGHT_STATUS_CANVAS = createCanvas({
        x: Player.width/2 + Global.MAP_SIZE.x/2 * Global.BLOCK_SIZE.x,
        y: 0,
        lifeTime: 0
    });

    initMap();
    initPlayer();

    Global.KEY_BLOCKED = false;
    Global.MOUSE_BLOCKED = false;
}

init();
editInit();
gameInit();
GUIInit();
timer(function() {
    initListener();
}, 500);
